### ISSUE TITLE
Error at build

### ISSUE THREAD

**Issue by oltmannsdaniel** [RnbWd/gulp-strip-comments#15]
When I use `.pipe(strip())` I get an Error:

```
C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:5618
            throw e;
            ^
 Error: Line 1: Unexpected token ILLEGAL
    at constructError (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:2406:21)
    at createError (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:2425:17)
    at unexpectedTokenError (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:2500:13)
    at throwUnexpectedToken (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:2504:15)
    at scanNumericLiteral (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:1041:13)
    at advance (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:1599:20)
    at collectToken (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:1634:17)
    at lex (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:1690:61)
    at Object.tokenize (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\esprima.js:5600:21)
    at Object.parseRegEx (C:\code\sandbox\sass\node_modules\gulp-strip-comments\node_modules\decomment\lib\utils.js:37:13)
```

Maybe someone can help me.

**Comment by vitaly-t** [comment]
That error relates to parsing JavaScript.

There must be something in your JavaScript that does not comply with ES6.
