### ISSUE TITLE
CSS decomment failing on basic run

### ISSUE THREAD

**Issue by davewallace** [RnbWd/gulp-strip-comments#19]
Receiving this error:

```
/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:3391
	            throw error;
	            ^
Error: Line 13: Unexpected token ILLEGAL
    at ErrorHandler.constructError (/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:3396:22)
    at ErrorHandler.createError (/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:3414:27)
    at ErrorHandler.throwError (/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:3422:21)
    at Scanner.throwUnexpectedToken (/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:3505:28)
    at Scanner.scanPunctuator (/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:4026:19)
    at Scanner.lex (/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:4628:22)
    at Tokenizer.getNextToken (/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:6366:43)
    at Object.tokenize (/Users/davew/dev/social/src/node_modules/esprima/dist/esprima.js:136:36)
    at Object.parseRegEx (/Users/davew/dev/social/src/node_modules/decomment/lib/utils.js:37:13)
    at parser (/Users/davew/dev/social/src/node_modules/decomment/lib/parser.js:35:27)
```

Parsing a CSS file that has known W3C validator errors in, but nothing that should be show-stopping. I found a few bad CSS hacks that would mess with comments perhaps, but upon removing them all, and then in turn removing *everything* except a single basic, valid selector - the above error continues to trigger.

I pushed my reduced test case to a repo here for you to peruse: https://github.com/davewallace/gulp-strip-comments-test

For comparison, I have since found the `gulp-strip-css-comments` package on NPM and switching this package out with theirs successfully removes the code comments.

**Comment by vitaly-t** [comment]
@davewallace That's because you are misusing the library.

This library relies on module [decomment](https://github.com/vitaly-t/decomment), which is far more generic and reusable than the component you switched to, as it was designed to remove all kinds of comments and from absolutely everything.

As per that component, it clearly states that for CSS you should be using method `.text`, to process CSS files the same as generic text files.

If you simply replace you call `stripComments()` with `stripComments.text()`, everything will work as expected.

**Comment by vitaly-t** [comment]
I have submitted a PR for your test project with the corection :wink:

**Comment by davewallace** [comment]
@vitaly-t thanks for that, my oversight - tested, merged & I've switched back to this module now :)
