### ISSUE TITLE
Unespected token ILLEGAL - esprima.js

### ISSUE THREAD

**Issue by Alecell** [RnbWd/gulp-strip-comments#20]
C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:3391
                    throw error;
                    ^
 Error: Line 1: Unexpected token ILLEGAL
    at ErrorHandler.constructError (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:3396:22)
    at ErrorHandler.createError (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:3414:27)
    at ErrorHandler.throwError (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:3422:21)
    at Scanner.throwUnexpectedToken (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:3505:28)
    at Scanner.scanPunctuator (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:4026:19)
    at Scanner.lex (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:4628:22)
    at Tokenizer.getNextToken (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:6366:43)
    at Object.tokenize (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\node_modules\esprima\dist\esprima.js:136:36)
    at Object.parseRegEx (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\lib\utils.js:37:13)
    at parser (C:\wamp\www\reiPallet\node_modules\gulp-strip-comments\node_modules\decomment\lib\parser.js:34:27)

I get this error message when try to run the gulp task, I tryed to solve the error but it was unsuccessful.

**Comment by vitaly-t** [comment]
So you must be sending an invalid javascript file into it.

**Comment by Alecell** [comment]
I just remove all the .js files in my project and get the same error.

**Comment by vitaly-t** [comment]
1. Find which file it complains about
2. Post either the while file here or the line where it complains
3. Post which `decomment` method you are using to process the file

The it will be possible to assist you further.

**Comment by sverrirs** [comment]
Same issue, there is a problem when you specify wildcards such as  '/*/**/' in the gulp.src preceding the strip task.

What happens is that the file discovery in the through.obj call goes up a directory and loads files from there.

Given this file structure
```
root
    src\
    dest\
    gulpfile.js
```

Using this gulp command
```
return gulp.src('dest/*/**''] )
    .pipe(strip())
    .pipe(gulp.dest('dest'));
```

Will actually load files from 'root/**' and not just from 'root/dest/'

**Comment by vitaly-t** [comment]
@sverrirs try `gulp-decomment` instead, which does the same ;)

**Comment by BuffMcBigHuge** [comment]
I solved this issue by removing commented lines inside arrays.

```
var myArray = [
   'item1',
//   'item2',
   'item3'
];
```

**Comment by jessedegans** [comment]
> @sverrirs try `gulp-decomment` instead, which does the same ;)

Produces exactly the same error though

**Comment by Mattnificent** [comment]
I am having this issue with private class members - for both gulp-decomment and gulp-strip-comments.  Perhaps the parser(s) used by these libs are not up to date with the latest [syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields).

**Comment by Mattnificent** [comment]
Nevermind those are a Node.js 12 language feature, and I'm using version 11!

**Comment by Mattnificent** [comment]
Well, updating node.js didn't fix the issue - but my error message looks nicer now
````
Node version:
16.14.0

[14:17:22] Error in plugin "gulp-strip-comments"
Message:
    Line 4773: Unexpected token ILLEGAL
Details:
    index: 308968
    lineNumber: 4773
    description: Unexpected token ILLEGAL
    fileName: C:\my\file\path.js
Process terminated with code 1.
````
